### ISSUE TITLE
Neden 150? 100 olması gerekmiyor mu?

### ISSUE THREAD

**Issue by evhar002** [hknylcnsy/Hakan-s-Ruin#1]
Aşağıdaki else kolu neden 150'ye bölünüyor?
`anaParadurumu -= anaParadurumu*(bahisYuzdesi / 150);`

**Comment by hknylcnsy** [comment]
Selamlar. Twitter'da da yazmıştım, botuma göre biraz ayar çektim diye. Bot satımlarda neredeyse 2 kat daha fazla efektif çalışıyor. Al dediğinde her zaman istediğim artışı yakalamasa da sat dediğinde çoğunlukla kayda değer bir biçimde düşüyor. O yüzden "150" ye böldüm

**Comment by evhar002** [comment]
Ben bir hata mı oldu düşüncesiyle yazdım, açıklama için teşekkürler.
